ALTER TABLE DOC
ADD SUMM NUMERIC (15,2)

ALTER TABLE typereestr
ADD SORTNUM INTEGER


CREATE TABLE CHAMBER
(
  CHAMBER_ID INTEGER NOT NULL,
  NAME VARCHAR(100) NOT NULL COLLATE PXW_CYRL,
  PRESIDENT VARCHAR(100) NOT NULL COLLATE PXW_CYRL,
  ADDRESS VARCHAR(250) NOT NULL COLLATE PXW_CYRL,
  PHONE VARCHAR(100) COLLATE PXW_CYRL,
  EMAIL VARCHAR(100) COLLATE PXW_CYRL
)

ALTER TABLE CHAMBER
ADD PRIMARY KEY (CHAMBER_ID)

CREATE GENERATOR SETCHAMBER_ID;

grant select, delete, insert, update on chamber to user_urdoc


CREATE TABLE NOTARY
(
  NOTARY_ID INTEGER NOT NULL,
  CHAMBER_ID INTEGER NOT NULL,
  FIO VARCHAR(100) NOT NULL COLLATE PXW_CYRL,
  ADDRESS VARCHAR(250) NOT NULL COLLATE PXW_CYRL,
  PHONE VARCHAR(100) COLLATE PXW_CYRL,
  EMAIL VARCHAR(100) COLLATE PXW_CYRL,
  COUNTY VARCHAR(250) COLLATE PXW_CYRL,
  LETTER VARCHAR(100) COLLATE PXW_CYRL,
  WORK_GRAPH VARCHAR(250) COLLATE PXW_CYRL
)

ALTER TABLE NOTARY
ADD IS_HELPER SMALLINT

ALTER TABLE NOTARY
ADD PRIMARY KEY (NOTARY_ID)

ALTER TABLE NOTARY
ADD FOREIGN KEY (CHAMBER_ID) REFERENCES CHAMBER (CHAMBER_ID)

CREATE GENERATOR SETNOTARY_ID;

grant select, delete, insert, update on NOTARY to user_urdoc


